///////////////////////////////////////////////////////////
//  IBolnicaProvider.cs
//  Implementation of the Interface IBolnicaProvider
//  Generated by Enterprise Architect
//  Created on:      29-Aug-2022 18:54:29
//  Original author: Luka
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Classes {
	public interface IBolnicaProvider  {

		/// 
		/// <param name="id"></param>
		Bolnica BolnicaSaID(int id);

		/// 
		/// <param name="bolnica"></param>
		void DodajBolnicu(Bolnica bolnica);

		/// 
		/// <param name="id"></param>
		/// <param name="bolnica"></param>
		void IzmeniBolnicu(int id, Bolnica bolnica);

		/// 
		/// <param name="id"></param>
		void ObrisiBolnicu(int id);

		List<Bolnica> SveBolnice();
	}//end IBolnicaProvider

}//end namespace Classes