///////////////////////////////////////////////////////////
//  IDodelaProvider.cs
//  Implementation of the Interface IDodelaProvider
//  Generated by Enterprise Architect
//  Created on:      29-Aug-2022 18:54:29
//  Original author: Luka
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Classes {
	public interface IDodelaProvider  {

		/// 
		/// <param name="pacijent"></param>
		/// <param name="lekar"></param>
		void Dodeli(Pacijent pacijent, Lekar lekar);

		/// 
		/// <param name="pacijent"></param>
		void Odjavi(Pacijent pacijent);

		/// 
		void Undo();

		/// 
		void Redo();
	}//end IDodelaProvider

}//end namespace Classes