///////////////////////////////////////////////////////////
//  IKorisnikProvider.cs
//  Implementation of the Interface IKorisnikProvider
//  Generated by Enterprise Architect
//  Created on:      29-Aug-2022 18:54:29
//  Original author: Luka
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Classes {
	public interface IKorisnikProvider  {

		/// 
		/// <param name="id"></param>
		Korisnik DobaviKorisnika(int id);

		/// 
		/// <param name="korisnik"></param>
		void DodajKorisnika(Korisnik korisnik);

		/// 
		/// <param name="id"></param>
		/// <param name="korisnik"></param>
		void IzmeniKorisnika(int id, Korisnik korisnik);

		/// 
		/// <param name="id"></param>
		void ObrisiKorisnika(int id);

		List<Korisnik> SviKorisnici();
	}//end IKorisnikProvider

}//end namespace Classes