///////////////////////////////////////////////////////////
//  IObavestenjeProvider.cs
//  Implementation of the Interface IObavestenjeProvider
//  Generated by Enterprise Architect
//  Created on:      01-Sep-2022 18:33:05
//  Original author: Luka
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

using Classes;
namespace Classes {
	public interface IObavestenjeProvider  {

		/// 
		/// <param name="obavestenje"></param>
		void DodajObavestenje(Obavestenje obavestenje);

		/// 
		/// <param name="korisnikId"></param>
		List<Obavestenje> Obavestenja(int korisnikId);


		/// 
		/// <param name="id"></param>
		void Procitano(int id);
	}//end IObavestenjeProvider

}//end namespace Classes