///////////////////////////////////////////////////////////
//  IDataProviderT.cs
//  Implementation of the Interface IPacijentProvider
//  Generated by Enterprise Architect
//  Created on:      29-Aug-2022 18:54:29
//  Original author: Luka
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Classes
{
	public interface IPacijentProvider
	{

		/// 
		/// <param name="id"></param>
		Pacijent Dobavi(int id);

		/// 
		/// <param name="obj"></param>
		void Dodaj(Pacijent obj);

		/// 
		/// <param name="id"></param>
		/// <param name="obj"></param>
		void Izmena(int id, Pacijent obj);

		/// 
		/// <param name="id"></param>
		void Obrisi(int id);

		List<Pacijent> Svi();
	}//end IPacijentProvider

}//end namespace Classes