///////////////////////////////////////////////////////////
//  IPregledProvider.cs
//  Implementation of the Interface IPregledProvider
//  Generated by Enterprise Architect
//  Created on:      29-Aug-2022 18:54:29
//  Original author: Luka
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Classes {
	public interface IPregledProvider  {
		/// 
		/// <param name="id"></param>
		void OdbijPregled(int id);

		/// 
		/// <param name="lekarID"></param>
		List<Termin> SviPregledi(int lekarID);

		/// 
		/// <param name="termin"></param>
		void ZakaziPregled(Termin termin);

		/// 
		/// <param name="id"></param>
		void ZapocniPregled(int id);

		/// 
		/// <param name="id"></param>
		void ZavrsiPregled(int id);
	}//end IPregledProvider

}//end namespace Classes
