///////////////////////////////////////////////////////////
//  ITerminController.cs
//  Implementation of the Interface ITerminProvider
//  Generated by Enterprise Architect
//  Created on:      29-Aug-2022 18:54:29
//  Original author: Luka
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace Classes {
	public interface ITerminProvider  {
		/// 
		/// <param name="id"></param>
		Termin Dobavi(int id);

		/// 
		/// <param name="termin"></param>
		void Dodaj(Termin termin);

		/// 
		/// <param name="id"></param>
		/// <param name="termin"></param>
		void Izmeni(int id, Termin termin);

		/// 
		/// <param name="id"></param>
		void Obrisi(int id);

		List<Termin> Svi();
	}//end ITerminProvider

}//end namespace Classes
