///////////////////////////////////////////////////////////
//  Command.cs
//  Implementation of the Class Command
//  Generated by Enterprise Architect
//  Created on:      29-Aug-2022 18:54:28
//  Original author: Luka
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Classes {
	public abstract class Command {

		public Command(){

		}

		~Command(){

		}

		public abstract void Execute();

		public abstract void Unexecute();

	}//end Command

}//end namespace Classes