///////////////////////////////////////////////////////////
//  ConcreteCommand.cs
//  Implementation of the Class ConcreteCommand
//  Generated by Enterprise Architect
//  Created on:      29-Aug-2022 18:54:28
//  Original author: Luka
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Classes;
namespace Classes {
	public abstract class ConcreteCommand : Command {

		protected Lekar lekar;
		protected Pacijent pacijent;
		public DodelaLekara m_DodelaLekara;

		public ConcreteCommand(){

		}

		~ConcreteCommand(){

		}

		/// 
		/// <param name="provider"></param>
		/// <param name="pacijent"></param>
		/// <param name="lekar"></param>
		public ConcreteCommand(DodelaLekara dodelaLekara, Pacijent pacijent, Lekar lekar){
			m_DodelaLekara = dodelaLekara;
			this.pacijent = pacijent;
			this.lekar = lekar;
		}

	}//end ConcreteCommand

}//end namespace Classes