///////////////////////////////////////////////////////////
//  DodelaLekara.cs
//  Implementation of the Class DodelaLekara
//  Generated by Enterprise Architect
//  Created on:      29-Aug-2022 18:54:29
//  Original author: Luka
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Data;
using MySql.Data.MySqlClient;
using Dapper;

namespace Classes {
	public class DodelaLekara {

		public DodelaLekara(){

		}

		~DodelaLekara(){

		}

		/// 
		/// <param name="pacijent"></param>
		/// <param name="lekar"></param>
		public void Dodeli(Pacijent pacijent, Lekar lekar){
			using (IDbConnection c = new MySqlConnection(ConnectionString.Read()))
			{
				c.Execute($"update pacijent set lekarId = @LekarID where id = @Id", new { Id = pacijent.Id, LekarID = lekar.Id });
				c.Execute($"insert into PacijentBolnica (bolnicaId, pacijentId) values (@BolnicaId, @PacijentId)", 
					new { BolnicaId = lekar.m_Bolnica.Id, PacijentId = pacijent.Id });
			}
		}

		/// 
		/// <param name="pacijent"></param>
		public void Odjavi(Pacijent pacijent){
			using (IDbConnection c = new MySqlConnection(ConnectionString.Read()))
			{
				c.Execute($"update pacijent set lekarId = @LekarID where id = @Id", new { Id = pacijent.Id, LekarID = -1 });
				c.Execute($"delete from PacijentBolnica where pacijentId = @PacijentId", new { PacijentId = pacijent.Id });
			}
		}

	}//end DodelaLekara

}//end namespace Classes