///////////////////////////////////////////////////////////
//  ObavestenjeProvider.cs
//  Implementation of the Class ObavestenjeProvider
//  Generated by Enterprise Architect
//  Created on:      01-Sep-2022 18:33:05
//  Original author: Luka
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Classes;
namespace Classes {
	public class ObavestenjeProvider : IObavestenjeProvider {

		public List<Obavestenje> m_Obavestenje;
		static int counter = 0;
		public ObavestenjeProvider(){
			m_Obavestenje = new List<Obavestenje>();
		}

		~ObavestenjeProvider(){

		}

		/// 
		/// <param name="obavestenje"></param>
		public void DodajObavestenje(Obavestenje obavestenje){
			obavestenje.Id = counter++;
			m_Obavestenje.Add(obavestenje);
		}

		/// 
		/// <param name="korisnikId"></param>
		public List<Obavestenje> Obavestenja(int korisnikId){
			return m_Obavestenje.FindAll(t => t.Korisnik.Id == korisnikId);
		}

        public void Procitano(int id)
        {
			m_Obavestenje.Remove(m_Obavestenje.Find(t => t.Id == id));
        }
    }//end ObavestenjeProvider

}//end namespace Classes