///////////////////////////////////////////////////////////
//  PregledProvider.cs
//  Implementation of the Class PregledProvider
//  Generated by Enterprise Architect
//  Created on:      29-Aug-2022 18:54:30
//  Original author: Luka
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Classes;
using MySql.Data.MySqlClient;
using Dapper;
using System.Data;

namespace Classes {
	public class PregledProvider : IPregledProvider {
		ITerminProvider terminProvider;

        public PregledProvider(){
			terminProvider = new TerminProvider();
        }
		public PregledProvider(ITerminProvider terminProvider){
			this.terminProvider = terminProvider;
		}

		~PregledProvider(){

		}

		/// 
		/// <param name="id"></param>
		public void OdbijPregled(int id)
		{
			var termin = terminProvider.Dobavi(id);
			termin.Odbij();
			terminProvider.Izmeni(termin.Id, termin);
		}

		/// 
		/// <param name="lekarID"></param>
		public List<Termin> SviPregledi(int lekarID)
		{
			return terminProvider.Svi().FindAll(t => t.Lekar.Id == lekarID);
		}

		/// 
		/// <param name="termin"></param>
		public void ZakaziPregled(Termin termin)
		{
			if (termin.DatumIVreme.DayOfWeek != DayOfWeek.Saturday && termin.DatumIVreme.DayOfWeek != DayOfWeek.Sunday &&
				termin.DatumIVreme.Hour > 8 && termin.DatumIVreme.Hour < 17)
			{
				terminProvider.Dodaj(termin);
			}
		}

		/// 
		/// <param name="id"></param>
		public void ZapocniPregled(int id)
		{
			var termin = terminProvider.Dobavi(id);
			termin.Zapocni();
			terminProvider.Izmeni(termin.Id, termin);
		}

		/// 
		/// <param name="id"></param>
		public void ZavrsiPregled(int id)
		{
			var termin = terminProvider.Dobavi(id);
			termin.Zavrsi();
			terminProvider.Izmeni(termin.Id, termin);
		}
	}//end PregledProvider

}//end namespace Classes
