///////////////////////////////////////////////////////////
//  Bolnica.cs
//  Implementation of the Class Bolnica
//  Generated by Enterprise Architect
//  Created on:      29-Aug-2022 18:54:28
//  Original author: mixa
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Classes;
namespace Classes {
	public class Bolnica {

		private int id;
		private int brojLekara;
		private int brojOdeljenja;
		private string naziv;
		private VrstaBolnice vrsta;
		public List<Lekar> m_Lekar;
		public List<Pacijent> m_Pacijent;

		public Bolnica(){

		}

        public Bolnica(int id, int brojLekara, int brojOdeljenja, string naziv, VrstaBolnice vrsta, List<Lekar> lekar, List<Pacijent> pacijent)
        {
            this.id = id;
            this.brojLekara = brojLekara;
            this.brojOdeljenja = brojOdeljenja;
            this.naziv = naziv;
            this.vrsta = vrsta;
            m_Lekar = lekar;
            m_Pacijent = pacijent;
        }

        ~Bolnica(){

		}

		public int Id
		{
			get
			{
				return id;
			}
			set
			{
				id = value;
			}
		}

		public int BrojLekara{
			get{
				return brojLekara;
			}
			set{
				brojLekara = value;
			}
		}

		public int BrojOdeljenja{
			get{
				return brojOdeljenja;
			}
			set{
				brojOdeljenja = value;
			}
		}

		public string Naziv{
			get{
				return naziv;
			}
			set{
				naziv = value;
			}
		}

		public VrstaBolnice Vrsta{
			get{
				return vrsta;
			}
			set{
				vrsta = value;
			}
		}

	}//end Bolnica

}//end namespace Classes