///////////////////////////////////////////////////////////
//  Korisnik.cs
//  Implementation of the Class Korisnik
//  Generated by Enterprise Architect
//  Created on:      29-Aug-2022 18:54:29
//  Original author: Luka
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Classes {
	public class Korisnik {

		protected int id;
		protected string ime;
		protected string korisnickoIme;
		protected string lozinka;
		protected string prezime;
		protected Tip tip;

		public Korisnik(){

		}

        public Korisnik(int id, string ime, string korisnickoIme, string lozinka, string prezime, Tip tip)
        {
            this.id = id;
            this.ime = ime;
            this.korisnickoIme = korisnickoIme;
            this.lozinka = lozinka;
            this.prezime = prezime;
            this.tip = tip;
        }

        ~Korisnik(){

		}

		public int Id{
			get{
				return id;
			}
			set{
				id = value;
			}
		}

		public string Ime{
			get{
				return ime;
			}
			set{
				ime = value;
			}
		}

		public string KorisnickoIme{
			get{
				return korisnickoIme;
			}
			set{
				korisnickoIme = value;
			}
		}

		public string Lozinka{
			get{
				return lozinka;
			}
			set{
				lozinka = value;
			}
		}

		public string Prezime{
			get{
				return prezime;
			}
			set{
				prezime = value;
			}
		}

		public Tip Tip{
			get{
				return tip;
			}
			set{
				tip = value;
			}
		}

	}//end Korisnik

}//end namespace Classes