///////////////////////////////////////////////////////////
//  Lekar.cs
//  Implementation of the Class Lekar
//  Generated by Enterprise Architect
//  Created on:      29-Aug-2022 18:54:29
//  Original author: mixa
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Classes;
namespace Classes {
	public class Lekar : Korisnik {

		private Odeljenje odeljenje;
		private Specijalizacija specijalizacija;
		private Titula titula;
		public Bolnica m_Bolnica;

		public Lekar(){

		}

        public Lekar(int id, string ime, string korisnickoIme, string lozinka, string prezime, Tip tip, Odeljenje odeljenje, Specijalizacija specijalizacija, Titula titula, Bolnica bolnica) : base(id, ime, korisnickoIme, lozinka, prezime, tip)
        {
			this.odeljenje = odeljenje;
			this.specijalizacija = specijalizacija;
			this.titula = titula;
			m_Bolnica = bolnica;
		}


        ~Lekar(){

		}

		public Odeljenje Odeljenje{
			get{
				return odeljenje;
			}
			set{
				odeljenje = value;
			}
		}

		public Specijalizacija Specijalizacija{
			get{
				return specijalizacija;
			}
			set{
				specijalizacija = value;
			}
		}

		public Titula Titula{
			get{
				return titula;
			}
			set{
				titula = value;
			}
		}

	}//end Lekar

}//end namespace Classes