///////////////////////////////////////////////////////////
//  Pacijent.cs
//  Implementation of the Class Pacijent
//  Generated by Enterprise Architect
//  Created on:      29-Aug-2022 18:54:30
//  Original author: mixa
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Classes;
namespace Classes {
	public class Pacijent : Korisnik {

		private string jmbg;
		private Lekar lekar;
		public Pacijent(){

		}

        public Pacijent(int id, string ime, string korisnickoIme, string lozinka, string prezime, Tip tip, string jmbg, Lekar lekar) : base(id, ime, korisnickoIme, lozinka, prezime, tip)
        {
			this.jmbg = jmbg;
			this.lekar = lekar;
        }

        ~Pacijent(){

		}

		public string JMBG{
			get{
				return jmbg;
			}
			set{
				jmbg = value;
			}
		}

		public Lekar Lekar
		{
			get
			{
				return lekar;
			}
			set
			{
				lekar = value;
			}
		}

	}//end Pacijent

}//end namespace Classes