///////////////////////////////////////////////////////////
//  Ceka.cs
//  Implementation of the Class Ceka
//  Generated by Enterprise Architect
//  Created on:      29-Aug-2022 18:54:28
//  Original author: Luka
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Classes;
namespace Classes {
    public class Ceka : StatusCekanja
    {
		public Ceka(){

		}

        ~Ceka(){

		}

        public override void Odbij(Termin termin)
        {
            ChangeState(termin, new Odbijen());
        }

        public override void Zapocni(Termin termin)
        {
            ChangeState(termin, new UToku());
        }

        public override void Zavrsi(Termin termin)
        {
            return;
        }
    }//end Ceka

}//end namespace Classes