///////////////////////////////////////////////////////////
//  Pregledan.cs
//  Implementation of the Class Pregledan
//  Generated by Enterprise Architect
//  Created on:      29-Aug-2022 18:54:30
//  Original author: Luka
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Classes;
namespace Classes {
	public class Pregledan : StatusCekanja {

		public Pregledan(){

		}

        ~Pregledan(){

		}

        public override void Odbij(Termin termin)
        {
            return;
        }

        public override void Zapocni(Termin termin)
        {
            return;
        }

        public override void Zavrsi(Termin termin)
        {
            return;
        }
    }//end Pregledan

}//end namespace Classes