///////////////////////////////////////////////////////////
//  StatusCekanja.cs
//  Implementation of the Class StatusCekanja
//  Generated by Enterprise Architect
//  Created on:      29-Aug-2022 18:54:30
//  Original author: Luka
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Classes {
	public abstract class StatusCekanja {
		public StatusCekanja()
		{

		}

		~StatusCekanja()
		{

		}

		/// 
		/// <param name="termin"></param>
		/// <param name="status"></param>
		public void ChangeState(Termin termin, StatusCekanja status)
		{
			termin.ChangeState(status);
		}

		/// 
		/// <param name="termin"></param>
		public abstract void Odbij(Termin termin);

		/// 
		/// <param name="termin"></param>
		public abstract void Zapocni(Termin termin);

		/// 
		/// <param name="termin"></param>
		public abstract void Zavrsi(Termin termin);


	}//end StatusCekanja

}//end namespace Classes