///////////////////////////////////////////////////////////
//  UToku.cs
//  Implementation of the Class UToku
//  Generated by Enterprise Architect
//  Created on:      29-Aug-2022 18:54:30
//  Original author: Luka
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Classes;
namespace Classes {
	public class UToku : StatusCekanja {

		public UToku(){

		}

        ~UToku(){

		}

        public override void Odbij(Termin termin)
        {
            return;
        }

        public override void Zapocni(Termin termin)
        {
            return;
        }

        public override void Zavrsi(Termin termin)
        {
            ChangeState(termin, new Pregledan());
        }
    }//end UToku

}//end namespace Classes