///////////////////////////////////////////////////////////
//  ConcreteObserver.cs
//  Implementation of the Class ConcreteObserver
//  Generated by Enterprise Architect
//  Created on:      29-Aug-2022 18:54:28
//  Original author: Luka
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Classes;
namespace Classes {
	public class ConcreteObserver : Observer {
		public IObavestenjeProvider m_ObavestenjeProvider;
		public ConcreteSubject m_ConcreteSubject;

		public ConcreteObserver(){

		}

        public ConcreteObserver(IObavestenjeProvider obavestenjeProvider, ConcreteSubject concreteSubject, Korisnik korisnik)
        {
            m_ObavestenjeProvider = obavestenjeProvider;
            m_ConcreteSubject = concreteSubject;
			m_Korisnik = korisnik;
        }

        ~ConcreteObserver(){

		}

		/// 
		/// <param name="tekst"></param>
		public override void Notify(){
			m_ObavestenjeProvider.DodajObavestenje(new Obavestenje(m_Korisnik, m_ConcreteSubject.Tekst));
		}

	}//end ConcreteObserver

}//end namespace Classes