///////////////////////////////////////////////////////////
//  Observer.cs
//  Implementation of the Class Observer
//  Generated by Enterprise Architect
//  Created on:      29-Aug-2022 18:54:30
//  Original author: Luka
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Classes {
	public abstract class Observer {

		public Korisnik m_Korisnik;

		public Observer(){

		}

		~Observer(){

		}

		/// 
		/// <param name="tekst"></param>
		public abstract void Notify();

	}//end Observer

}//end namespace Classes