///////////////////////////////////////////////////////////
//  KorisnikStrategy.cs
//  Implementation of the Class KorisnikStrategy
//  Generated by Enterprise Architect
//  Created on:      29-Aug-2022 18:54:29
//  Original author: Luka
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Classes {
	public class KorisnikStrategy {

		private static IKorisnikProvider korisnikStrategy;

		public KorisnikStrategy(){

		}

		~KorisnikStrategy(){

		}

		public static IKorisnikProvider GetStrategy(){

			return korisnikStrategy;
		}

		/// 
		/// <param name="korisnikProvider"></param>
		public static void SetStrategy(IKorisnikProvider korisnikProvider){
			korisnikStrategy = korisnikProvider;
		}

	}//end KorisnikStrategy

}//end namespace Classes