///////////////////////////////////////////////////////////
//  Odeljenje.cs
//  Implementation of the Enumeration Odeljenje
//  Generated by Enterprise Architect
//  Created on:      29-Aug-2022 18:54:30
//  Original author: Luka
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Classes {
	public enum Odeljenje : int {

		Hirurgija,
		Ortopedija,
		Pedijatrija,
		Opsta

	}//end Odeljenje

}//end namespace Classes