///////////////////////////////////////////////////////////
//  Tip.cs
//  Implementation of the Enumeration Tip
//  Generated by Enterprise Architect
//  Created on:      29-Aug-2022 18:54:30
//  Original author: Luka
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Classes {
	public enum Tip : int {

		Lekar,
		Pacijent,
		Administrator

	}//end Tip

}//end namespace Classes