///////////////////////////////////////////////////////////
//  VrstaBolnice.cs
//  Implementation of the Enumeration VrstaBolnice
//  Generated by Enterprise Architect
//  Created on:      29-Aug-2022 18:54:30
//  Original author: Luka
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Classes {
	public enum VrstaBolnice : int {

		DomZdravlja,
		Ambulanta

	}//end VrstaBolnice

}//end namespace Classes